### PR TITLE
feat: support live TTS of fish audio

### PR DESCRIPTION
**Pull request by frostming**
Signed-off-by: Frost Ming <me@frostming.com>

### CODE REVIEW

**Comment by yihong0618** [comment]
voice always the same
@frostming no matter how to change the voice id

**Comment by yihong0618** [comment]
@frostming

**Comment by frostming** [comment]
It seems like an upstream issue. The voice is not changeable in websocket mode via `reference_id` config @abersheeran

**Comment by abersheeran** [comment]
> It seems like an upstream issue. The voice is not changeable in websocket mode via `reference_id` config @abersheeran

已经复现，转交给相关同事在看了。

**Comment by abersheeran** [comment]
验证过了，已经修复。

**Comment by yihong0618** [comment]
现在的情况是不播放了。。。

**Comment by abersheeran** [comment]
测了几遍都没问题，能不能看看具体是什么错误？网络？返回的二进制不是音频流？还是提前中断？

**Comment by frostming** [comment]
> 测了几遍都没问题，能不能看看具体是什么错误？网络？返回的二进制不是音频流？还是提前中断？

Traceback (most recent call last):
  File "/Users/fming/wkspace/github/tetos/.venv/lib/python3.11/site-packages/fish_audio_sdk/websocket.py", line 135, in tts
    message = await ws.receive_bytes()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fming/wkspace/github/tetos/.venv/lib/python3.11/site-packages/httpx_ws/_api.py", line 883, in receive_bytes
    event = await self.receive(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fming/wkspace/github/tetos/.venv/lib/python3.11/site-packages/httpx_ws/_api.py", line 805, in receive
    raise WebSocketDisconnect(event.code, event.reason)
httpx_ws._exceptions.WebSocketDisconnect: (<CloseReason.NO_STATUS_RCVD: 1005>, '')

**Comment by abersheeran** [comment]
明白了，你是手写的一个参数字典。之前 api 校验时默认值没处理好导致缺了个参数无法通过校验，现在滚动更新上去了。

**Pull request merged**
