### PR TITLE
Add the Microsoft TTS support

### PR DESCRIPTION
**Pull request by pjq**
Add the Microsoft TTS support

```
Serving on 192.168.31.29:8075
Running xiaogpt now, 用`帮我`开头来提问

ENABLE_IMMERSIVE_TALKING_MODE: 中国有哪些好玩的地方用英语回答
以下是小爱的回答:  这个小爱还在学习呢，不如你问我，你会做什么，先了解一下我的功能吧
以下是GPT的回答: 

There are many amazing places to visit in China, some of which include:

1. The Great Wall of China – This world-famous landmark is one of China’s most iconic attractions and a must-see for anyone visiting the country.

2. The Terracotta Warriors – These ancient statues are a testament to the incredible craftsmanship and history of China’s past.

3. The Forbidden City – This magnificent palace complex was once the home of China’s emperors and is a fascinating glimpse into the country’s imperial past.

4. Chengdu Panda Base – This conservation and research center is dedicated to protecting China’s beloved giant pandas.

5. The Yangtze River – China’s longest river is a breathtaking sight, offering visitors the chance to explore stunning scenery and historic towns.

6. Zhangjiajie National Forest Park – This unique park features towering sandstone pillars, lush forests, and incredible natural beauty.

7. The Yungang Grottoes – These ancient caves are filled with stunning Buddhist sculptures and carvings dating back to the 5th century AD.

8. The Leshan Giant Buddha – This impressive statue is the largest Buddha in the world and stands over 71 meters tall.

9. Jiuzhaigou Valley – This stunning national park is known for its crystal-clear lakes, waterfalls, and incredible natural beauty.

10. Guilin – This picturesque city is surrounded by stunning scenery, including the famous limestone karst mountains and the beautiful Li River.
ms_tts
text2mp3 
Speech synthesized to speaker for text [

There are many amazing places to visit in China, some of which include:

1. The Great Wall of China – This world-famous landmark is one of China’s most iconic attractions and a must-see for anyone visiting the country.

2. The Terracotta Warriors – These ancient statues are a testament to the incredible craftsmanship and history of China’s past.

3. The Forbidden City – This magnificent palace complex was once the home of China’s emperors and is a fascinating glimpse into the country’s imperial past.

4. Chengdu Panda Base – This conservation and research center is dedicated to protecting China’s beloved giant pandas.

5. The Yangtze River – China’s longest river is a breathtaking sight, offering visitors the chance to explore stunning scenery and historic towns.

6. Zhangjiajie National Forest Park – This unique park features towering sandstone pillars, lush forests, and incredible natural beauty.

7. The Yungang Grottoes – These ancient caves are filled with stunning Buddhist sculptures and carvings dating back to the 5th century AD.

8. The Leshan Giant Buddha – This impressive statue is the largest Buddha in the world and stands over 71 meters tall.

9. Jiuzhaigou Valley – This stunning national park is known for its crystal-clear lakes, waterfalls, and incredible natural beauty.

10. Guilin – This picturesque city is surrounded by stunning scenery, including the famous limestone karst mountains and the beautiful Li River.]
play: http://192.168.31.29:8075/msoutput.mp3
192.168.31.64 - - [06/Mar/2023 23:24:48] "GET /msoutput.mp3 HTTP/1.1" 200 -

```

### CODE REVIEW

**Comment by yihong0618** [comment]
this seems a little slow?

**Comment by pjq** [comment]
> this seems a little slow?
Yes, it could be.
The tts quality is much better.

**Comment by yihong0618** [comment]
I think maybe we can choose a service that is open source not MS's service
for users its hard to get the token

**Comment by yihong0618** [comment]
by the way I check the code, its very nice!

**Comment by yihong0618** [comment]
> by the way I check the code, its very nice!

and clever

**Comment by pjq** [comment]
The Microsoft TTS is free for 500,000 characters/month.

**Comment by yihong0618** [comment]
> The Microsoft TTS is free for 500,000 characters/month.

yes...for normal users the hard part is login and get the token
I wonder there must be some free and no token service

**Comment by pjq** [comment]
The Bob Translator integrate those tts engine

image

**Comment by yihong0618** [comment]
offline seems enough?

**Comment by yihong0618** [comment]
OK sounds reasonable

**Comment by yihong0618** [comment]
@pjq found it https://github.com/rany2/edge-tts

**Comment by pjq** [comment]
Just testing, seems we can do the integration now.

**Comment by yihong0618** [comment]
@pjq I will use some of your code and edge-tts to support it thanks～

**Comment by yihong0618** [comment]
@pjq 
closing this will use #139 instead

**Pull request closed without merging**
